FROM openjdk:11
COPY splunk-otel-javaagent.jar /splunk-otel-javaagent.jar
COPY ./out/artifacts/consumer_jar/ReviewsConsumerToMongo.jar /ReviewsConsumerToMongo.jar
CMD ["java", "-javaagent:./splunk-otel-javaagent.jar", "-Dsplunk.profiler.enabled=true", "-Dsplunk.profiler.period.threaddump=1000", "-Dsplunk.metrics.enabled=true", "-jar", "-Dotel.instrumentation.common.experimental.suppress-messaging-receive-spans=true", "ReviewsConsumerToMongo.jar"]

#docker build -f Dockerfile.ReviewsConsumerToMongo -t localhost:8000/reviewsconsumertomongo-splkotel:1.0 . 2> /tmp/dockerbuild_log.txt
#docker push localhost:8000/reviewsconsumertomongo-splkotel:1.0
