FROM openjdk:11
COPY splunk-otel-javaagent.jar /splunk-otel-javaagent.jar
COPY ReviewsProducer.jar /ReviewsProducer.jar
CMD ["java", "-javaagent:./splunk-otel-javaagent.jar", "-Dsplunk.profiler.enabled=true", "-Dsplunk.metrics.enabled=true", "-jar", "ReviewsProducer.jar"]

#docker build -f Dockerfile.ReviewsProducer -t localhost:8000/reviewsproducer-splkotel:0.01 .
#docker push localhost:8000/reviewsproducer-splkotel:0.01
