FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
RUN pip install splunk-opentelemetry[all]
RUN splk-py-trace-bootstrap

COPY ./sentiment.py /app

EXPOSE 5001
ENTRYPOINT [ "splunk-py-trace" ]
CMD [ "python", "sentiment.py" ]

#docker build -f Dockerfile.sentiment -t localhost:8000/sentiment-splkotel:0.01 .
#docker push localhost:8000/sentiment-splkotel:0.01