FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY ./sentiment.py /app

EXPOSE 5001
CMD [ "python", "sentiment.py" ]

#docker build -t localhost:8000/sentiment:0.01 .
#docker push localhost:8000/sentiment:0.01