FROM docker.io/openjdk:11
COPY ReviewsConsumerToMongo.jar /ReviewsConsumerToMongo.jar
CMD ["java", "-jar", "ReviewsConsumerToMongo.jar"]

#docker build -f Dockerfile.ReviewsConsumerToMongo.metrics -t localhost:8000/reviewsconsumertomongo:0.01 .
#docker push localhost:8000/reviewsconsumertomongo:0.01
