FROM docker.io/openjdk:11
COPY ReviewsProducer.jar /ReviewsProducer.jar
CMD ["java", "-jar", "ReviewsProducer.jar"]

#docker build -f Dockerfile.ReviewsProducer -t localhost:8000/reviewsproducer:0.01 .
#docker push localhost:8000/reviewsproducer:0.01
