apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kafka
  name: kafka-headless-sl
  namespace: default
spec:
  ports:
  - name: tcp-client
    port: 9092
    protocol: TCP
    targetPort: kafka-client
    nodePort: 30092
  - name: tcp-internal
    port: 9093
    protocol: TCP
    targetPort: kafka-internal
    nodePort: 30093
  selector:
    app.kubernetes.io/name: kafka
  type: NodePort
status:
