FROM python:3.10-slim

WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt

COPY ./business_lookup.py /app

EXPOSE 5002
CMD [ "python", "business_lookup.py" ]

#docker build -f Dockerfile.businesslookup -t localhost:8000/businesslookup:0.01 .
#docker push localhost:8000/businesslookup:0.01